max_pagination: 2
view_product_detail_css: ".car-item"
item_image_urls_css: ".highslide-gallery"
item_image_urls_xpath: ".//img/@src"
info_containers_css: "#mail_parent"
info_key: ".//label/text()"
info_val_container: ".inp"
info_val_checkbox: "./input"
info_val_checkbox_content: "./input/@checked"
info_val_text_content: "./text()"
item_brand_xpath: "//span[@itemprop=\"itemListElement\"][3]//span[@itemprop=\"name\"]/strong/text()"
item_serie_xpath: "//span[@itemprop=\"itemListElement\"][4]//span[@itemprop=\"name\"]/strong/text()"
item_model_year_xpath: "//span[@itemprop=\"itemListElement\"][5]//span[@itemprop=\"name\"]/strong/text()"
item_price_vnd_xpath: "//*[@id=\"car_detail\"]/div[3]/h1/text()"
item_price_dol_xpath: "//*[@id=\"car_detail\"]/div[3]/h1/font/text()"
item_description_css: ".des_txt::text"
